### ISSUE TITLE
[release] Open-leaderboard version 0.1 online

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-leaderboard#1]
We plan to release Open-leaderboard version 0.1 this month.

Any suggestions can be discussed in this repo.

例如，域名需要修改：http://open-insight-index.x-lab.info/

to：http://open-leaderboard.x-lab.info/

**Comment by gymgym1212** [comment]
For now, domain name has changed to http://open-leaderboard.x-lab.info/
http://open-insight-index.x-lab.info/ is closed

**Comment by maninhill** [comment]
When is the v1.0 version expected to be officially released?

**Comment by gymgym1212** [comment]
Hi @maninhill, I think it would be released in this month.

**Comment by maninhill** [comment]
多谢。另外 open-leaderboard 上面目前还是 2月份的数据，3月份的数据预计是什么时候更新，或者更新规律是什么？

**Comment by gymgym1212** [comment]
The data of March has been updated.
In the future, we will make the data automatically updated at the beginning of the month through some automatic work.

**Comment by maninhill** [comment]
四月份的数据方便时帮忙更新下:)

**Comment by gymgym1212** [comment]
> 四月份的数据方便时帮忙更新下:)
Now the data will be updated automatically, and the data of last month will be updated from the 5th to the 10th of each month. :)

**Comment by maninhill** [comment]
> > 四月份的数据方便时帮忙更新下:)
> 
> Now the data will be updated automatically, and the data of last month will be updated from the 5th to the 10th of each month. :)

That's great.

**Comment by maninhill** [comment]
四月份数据已经可以查了，但是默认显示的还是 3月份的数据。

<img width="884" alt="image" src="https://user-images.githubusercontent.com/41712985/167120642-14bc6a7f-5932-4cab-b245-c7ed9020a5fe.png">

**Comment by gymgym1212** [comment]
Since it has been released, close this issue
