### ISSUE TITLE
[Feature] support XSOSI large screen

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-leaderboard#100]
### Description

I suggest we can add XSOSI large screen in  Insight Board module.

The link of XSOSI large screen：https://dataease.x-lab.info/link/E1OQKVBz

**Comment by wj23027** [comment]
That's a good idea. I'll add XSOSI large screen to the Insight Board module module as soon as possible.

**Comment by tyn1998** [comment]
Please also count X-lab OSPO dashboard in :)

link: https://dataease.x-lab.info/link/N1fjcnVD

<img width="1507" alt="image" src="https://github.com/X-lab2017/open-leaderboard/assets/32434520/c249378f-5adc-4ba7-ab3f-31ff9579ff6d">

**Comment by wj23027** [comment]
> Please also count X-lab OSPO dashboard in :)

OK~

**Comment by wj23027** [comment]
@zhicheng-ning @tyn1998 I have written introductions for both dashboards. Is there anything that needs adjustment?
 
#### XSOSI 大屏
XSOSI 大屏用于呈现与 XSOSI 项目相关的各项指标和数据。大屏展示了参与人数、当前期数、组织总数和项目总数等基本指标。此外，还呈现了项目最新的 Openrank 分布图表、个人 Openrank 榜单、项目最新 Openrank 榜单、项目全域 Openrank 总值月度变化图表等。通过XSOSI大屏，用户可以了解贡献者的排名和津贴，项目的整体贡献情况，从激励更多成员积极参与到项目中，推动开源项目的发展和繁荣。

#### OSPO 大屏
OSPO 大屏主要展示了企业和组织在开源领域的活跃情况。该大屏不仅提供了企业和组织在 GitHub 开源项目中的活跃度、star数、新增issue数等指标，还呈现了 Opendigger 指标明细、OpenRank 比较等详细数据。此外，大屏还展示了羽雀空间的数据以及在开源领域的论文发表情况。通过 OSPO 大屏，用户能够全面了解组织和企业在开源领域的活跃情况，从而促进与开源社区的合作和发展。

**Comment by tyn1998** [comment]
> #### OSPO 大屏
> OSPO 大屏主要展示了企业和组织在开源领域的活跃情况。该大屏不仅提供了企业和组织在 GitHub 开源项目中的活跃度、star数、新增issue数等指标，还呈现了 Opendigger 指标明细、OpenRank 比较等详细数据。此外，大屏还展示了羽雀空间的数据以及在开源领域的论文发表情况。通过 OSPO 大屏，用户能够全面了解组织和企业在开源领域的活跃情况，从而促进与开源社区的合作和发展。

谢谢 @wj23027，咱这个是”X-lab OSPO“大屏，所以描述可以针对[X-lab OSPO本身的功能](https://github.com/X-lab2017/open-wonderland/issues/250#issuecomment-1502629967)来进行，我认为不用上升到”企业和组织“。另外，是”语雀“而不是”羽雀“ :D

**Comment by zhicheng-ning** [comment]
> 项目全域 Openrank 总值月度变化图表等。通过XSOSI大屏，用户可以了解贡献者的排名和津贴，项目的整体贡献情况，从激励更

- OpenRank
- 从而

**Comment by wj23027** [comment]
参考@zhicheng-ning @tyn1998给出的意见，这是修改后的版本~

#### XSOSI 大屏
XSOSI 大屏用于呈现与 XSOSI 项目相关的各项指标和数据。大屏展示了参与人数、当前期数、组织总数和项目总数等基本指标。此外，还呈现了项目最新的 OpenRank 分布图表、个人 OpenRank 榜单、项目最新 OpenRank 榜单、项目全域 OpenRank 总值月度变化图表等。通过 XSOSI 大屏，用户可以了解贡献者的排名和津贴，项目的整体贡献情况，从而激励更多成员积极参与到项目中，推动开源项目的发展和繁荣。

#### OSPO 大屏
X-lab OSPO 大屏主要展示了 X-lab 在开源领域的活跃情况。大屏不仅提供了 X-lab 在 GitHub 开源项目中的活跃度、新增 Star 数、新增 Issue 数等基础指标，还呈现了 OpenDigger 指标明细、OpenRank 比较等详细数据。此外，大屏还展示了 X-lab 在语雀空间的数据以及在开源领域的论文发表情况。通过 X-lab OSPO 大屏，用户能够全面了解 X-lab 在开源领域的活跃情况，进而促进与开源社区的合作和发展。
