### ISSUE TITLE
目前官网数据仍然停止在2023年10月份，能否更新下？

### ISSUE THREAD

**Issue by maninhill** [X-lab2017/open-leaderboard#107]
### Description

![image](https://github.com/X-lab2017/open-leaderboard/assets/41712985/a1ac7cb2-a80e-4e7d-a9d3-9896b2381abb)

**Comment by andyhuang18** [comment]
>由于 OpenDigger 底层数据层最近接入 Gitee 数据，部分代码需进行调整重构，本月所有数据指标发布将延后一周左右，届时将同时发布 GitHub 与 Gitee 数据指标，可能影响到所有下游应用。

Open Leaderboard的数据是基于OpenDigger的，所以也有一定的延迟。抱歉～
