### ISSUE TITLE
[Bug] Scroll to top button visibility

### ISSUE THREAD

**Issue by Apurv428** [X-lab2017/open-leaderboard#109]
### Current Behavior

Without scrolling, scroll to top button is seen

### Expected Behavior

The scroll to top button should be seen after scrolling

### Environment

```markdown
- OS: Windows
- Browser: Brave, Chrome
```

**Comment by andyhuang18** [comment]
Hi~@Apurv428 .Thank you for your issue. This problem is small, but it is also very important! I will review your PR. Thank you for your contribution and efforts~
