### ISSUE TITLE
[UI] Regarding Q & A Section

### ISSUE THREAD

**Issue by Apurv428** [X-lab2017/open-leaderboard#117]
### Description

Currently, the close icon is at bottom of question and answer section, the closing icon is at bottom. Instead of it is better to have it at top to the right of the title (Q&A)

Current Behavior:

https://github.com/X-lab2017/open-leaderboard/assets/84929607/37969939-a289-4295-bf6f-f06252dce902

**Comment by wj23027** [comment]
Thanks for the great suggestion! And the modals in the upper right corner, like the Insight Board and the glossary, all use the same design, they definitely need some adjustments.

![1716170685781](https://github.com/X-lab2017/open-leaderboard/assets/62098023/bbe65f48-457b-4e21-aa66-baa08614373a)

**Comment by Apurv428** [comment]
> Thanks for the great suggestion! And the modals in the upper right corner, like the Insight Board and the glossary, all use the same design, they definitely need some adjustments.
> 
> ![1716170685781](https://private-user-images.githubusercontent.com/62098023/331921884-bbe65f48-457b-4e21-aa66-baa08614373a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODYzMjIsIm5iZiI6MTcxNjE4NjAyMiwicGF0aCI6Ii82MjA5ODAyMy8zMzE5MjE4ODQtYmJlNjVmNDgtNDU3Yi00ZTIxLWFhNjYtYmFhMDg2MTQzNzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNzEzNzI5MmQ5YTRiODkwNGI3ZTkxNGJmYmVmYjE4NDliYzRlOGRkNWFlMTQ1OWJkMmNlYTIzNTMzNDgxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TW27k2XiMcD6RZB0z1JoS2yJPeAl_ggExwLEmk7Td20)

I will look into them too. Thanks for pointing out!
