### ISSUE TITLE
[Bug] Fit2Cloud 点击大屏没有数据

### ISSUE THREAD

**Issue by ibuler** [X-lab2017/open-leaderboard#142]
### Current Behavior

点击 Fit2Cloud 大屏按钮，大屏没有数据，别的项目是有的

![image](https://github.com/user-attachments/assets/9dd66de2-a2bc-4c9d-bc90-d61a598e54a7)

![image](https://github.com/user-attachments/assets/32823190-fd67-4286-a233-be363358286d)

### Environment

```markdown
- OS: macOS 14
- Browser: Chrome 131.0.6778.71（正式版本） (arm64)
```

**Comment by andyhuang18** [comment]
抱歉，在数据整理时遗漏了，我会修改这个问题。
