### ISSUE TITLE
[feature] Add GitHub link

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-leaderboard#2]
Just like https://opensource.win/, we can add a GitHub repo link to the page to direct user feedback.

![image](https://user-images.githubusercontent.com/15010826/159191140-a570f043-ac82-4879-84e6-40f42141ecdc.png)

**Comment by gymgym1212** [comment]
Now the open-leaderboard has a GitHub icon on the right at the end of the page, which links to OpenDigger repo.

It seems that we should make user come to here to do some feedback?

**Comment by kongzhongsanbu** [comment]
Maybe we could add a GitHub icon to the end of header, and let it links to OpenLeaderboard Repo.

<img width="418" alt="1647837007(1)" src="https://user-images.githubusercontent.com/44364729/159205691-a9689f06-e6fc-4026-9eca-363779289e66.png">

As for OpenDigger repo,  we could click the Logo below to it.
![image](https://user-images.githubusercontent.com/44364729/159206344-04fd7ab2-605c-4cc2-b085-3aae87270ce3.png)
