### ISSUE TITLE
[i18n] International version of OpenLeaderboard

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-leaderboard#20]
As [Open Source Summit North America 2022](https://events.linuxfoundation.org/open-source-summit-north-america/) is approaching, and we want to release the international version of this product.

So, could you setup the bilingual website with comminity contribitors no later than **June 21** ? @gymgym1212  

Many thanks~

**Comment by gymgym1212** [comment]
This is urgent and I will do it as soon as possible.

**Comment by will-ww** [comment]
> This is urgent and I will do it as soon as possible.

Many thanks~
