### ISSUE TITLE
[information update] What is X-lab?

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-leaderboard#30]
What is X-lab? (old)

X-Lab is a combination of two leading and pioneering laboratories from computer science and data science and engineering respectively in Tongji University and East China Normal University.The lab is supported by a number of core members, including doctorial supervisors, Ph.D students, master students and undergraduate students. X-Lab is an intercross multi-discipline, cutting-edge research lab which focuses on the following research domains: Cloud Computing, Big Data, Data Intelligence, and Education Science & Technology.

to:

X-lab is an open group for open-source research and innovation, connected by experts, scholars and engineers from universities, startups, and IT companies at home and abroad. Professional backgrounds include software engineering, data science, business administration, economics and other interdisciplinary fields. It performs long-term thinking and practice of open source strategy, open source measurement, open source digital ecosystems and other topics, and has also made influential work in areas including open source governance standards development, community behavioral metrics and analysis, and data governance.

**Comment by gymgym1212** [comment]
王老师可以再提供一下中文的版本吗？

**Comment by will-ww** [comment]
> 王老师可以再提供一下中文的版本吗？

实际上，在中文版的基础上做了点略微修改的：https://xlab2017.yuque.com/msdpvs/me6vqg/tkfb4c
