### ISSUE TITLE
[Bug] 根据企业名称拼得的url不一定正确

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-leaderboard#34]
Hi, @gymgym1212, 我来反馈一下~

比如：

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/32434520/174704479-9f285b79-c3da-4763-ae63-b52b6bc22347.png">

结果是：

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/32434520/174704545-782f8f92-d750-43dc-ab0a-ec3316c628fa.png">

又如：github.com/JD其实是一个用户。

**Comment by frank-zsy** [comment]
基于标签的数据，例如企业数据，是没有办法直接获取 GitHub 地址的，因为每个标签下面都含有多个 org 或 repo。可以先去掉这里的 URL 跳转，更好的方式获取是在点击时跳出一个浮窗显示其包含的所有组织和项目列表。

**Comment by tyn1998** [comment]
难怪之前试的时候有发现过超链接都不见的情况

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Yeming Gu ***@***.***>
发送时间: Thursday, June 23, 2022 1:20:56 AM
收件人: X-lab2017/open-leaderboard ***@***.***>
抄送: Lam Tang ***@***.***>; Author ***@***.***>
主题: Re: [X-lab2017/open-leaderboard] [Bug] 根据企业名称拼得的url不一定正确 (Issue #34)


Closed #34<https://github.com/X-lab2017/open-leaderboard/issues/34> as completed.

―
