### ISSUE TITLE
[doc] 重磅发布前需要更新一下README~

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-leaderboard#35]
我猜 @gymgym1212 肯定安排上了，这issue我帮你开了哈哈

**Comment by will-ww** [comment]
> 我猜 @gymgym1212 肯定安排上了，这issue我帮你开了哈哈

一起一起，我也参与哈，有需要合并什么的，可以找我哈~

**Comment by gymgym1212** [comment]
@tyn1998 谢谢圆场，哈哈哈哈。README中有关开发的部分我来写，其他的介绍文案和相关资料，大家帮忙补充一下吧

**Comment by maninhill** [comment]
请问正式发布时间大概是什么时候？
