### ISSUE TITLE
[task] 我们需要配置一个 SSL 的证书

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-leaderboard#4]
如图所示：

![f0e1c281a07c7af27016d038a0127fc](https://user-images.githubusercontent.com/15010826/159290522-b48f909e-f212-422e-9656-fe537795ce8f.png)

**Comment by gymgym1212** [comment]
Yes, we need a ssl certificate! 

The solution is: 
step1, someone who have the right to manage ssl certificates should visit the aliyun oss console page and choose this bucket, then click the domain name management tab.
![image](https://user-images.githubusercontent.com/37684061/159647393-df272d78-6ece-48f0-ade2-609b7cdc56be.png)

step2, click the button to config ssl trust.
![image](https://user-images.githubusercontent.com/37684061/159647813-9d4ae70d-c25e-4c52-9dc7-10eddd1c3d64.png)

![image](https://user-images.githubusercontent.com/37684061/159647742-729f8f94-3b5e-4193-8bb9-b7c4a0ad1493.png)

I think @ShiJingbeng or @frank-zsy can make this operation.

**Comment by gymgym1212** [comment]
OK, the job has been handed over to ShiJingbeng

**Comment by frank-zsy** [comment]
I have added the SSL certificate and should be already take effect, try to visit https://open-leaderboard.x-lab.info/

**Comment by gymgym1212** [comment]
OK, @frank-zsy  thanks a lot!
