### ISSUE TITLE
[Feature] Adding Project Insight link

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-leaderboard#48]
We can also add a GitHub Hypercrx link to the projects ranking list to attract more Hypercrx users~

![image](https://user-images.githubusercontent.com/15010826/178207137-246ce688-1325-4c69-81a4-5d827236d848.png)

Or we can first show a dashboard to demostrate the metircs, such as:

![image](https://user-images.githubusercontent.com/15010826/178212721-5d818386-eb4e-40cf-9159-92d44a13b437.png)

and then, if a user want more detail information, he can use the Hypercrx to oberserve.

And the dashboard can be a building block both in OpenLeaderboard and Hypercrx~

**Comment by zhicheng-ning** [comment]
Hello，@andyhuang18 @wj23027:laughing:. Could you finish this feature which add a column of links ? 

- If you have any code problem when you develop, you can request help of @gymgym1212 and @tyn1998 who are good at front-end.
- If you have any problem about feature or contact with back-end, you can ask me.

OpenLeaderBoard Source Code Introduction：
https://meeting.tencent.com/v2/cloud-record/share?id=0873afd7-e0ad-4104-aef0-a18265f3faf8&from=3

![image](https://user-images.githubusercontent.com/39022409/217441593-b411ebfb-8fda-49ee-b10b-5db60b47807c.png)

**Comment by andyhuang18** [comment]
OK~I will finish this feature as soon as possible

**Comment by wj23027** [comment]
OK，I will finish this feature with @andyhuang18 ~

**Comment by andyhuang18** [comment]
志成学长，我想问一下跳转DataEase大屏的url格式是什么呀，以Paddle项目在2023年1月数据为例。

**Comment by zhicheng-ning** [comment]
> 志成学长，我想问一下跳转DataEase大屏的url格式是什么呀，以Paddle项目在2023年1月数据为例。

参考外部参数这篇文档https://dataease.io/docs/user_manual/dashboard_basicfunctions/?h=%E5%A4%96%E9%83%A8%E5%8F%82%E6%95%B0#7，传入参数 {"org_name":"dataease","repo_name":"dataease","t_month":"2022-12-01"}，得到的链接：http://dataease.nzcer.cn/link/LeMILNSw?attachParams=eyJvcmdfbmFtZSI6ImRhdGFlYXNlIiwicmVwb19uYW1lIjoiZGF0YWVhc2UiLCJ0X21vbnRoIjoiMjAyMi0xMi0wMSJ9。所以需要前端对入参做一个加密，然后通过字符串传参给到后端链接

**Comment by andyhuang18** [comment]
> > 志成学长，我想问一下跳转DataEase大屏的url格式是什么呀，以Paddle项目在2023年1月数据为例。
> 
> 参考外部参数这篇文档[dataease.io/docs/user_manual/dashboard_basicfunctions/?h=%E5%A4%96%E9%83%A8%E5%8F%82%E6%95%B0#7](https://dataease.io/docs/user_manual/dashboard_basicfunctions/?h=%E5%A4%96%E9%83%A8%E5%8F%82%E6%95%B0#7) ，传入参数 {"org_name":"dataease","repo_name":"dataease","t_month":"2022-12-01"}，得到的链接：http://dataease.nzcer.cn/link/LeMILNSw?attachParams=eyJvcmdfbmFtZSI6ImRhdGFlYXNlIiwicmVwb19uYW1lIjoiZGF0YWVhc2UiLCJ0X21vbnRoIjoiMjAyMi0xMi0wMSJ9 。 所以需要前端对入参做一个加密，然后通过字符串传参给到后端链接

 好的！

**Comment by zhicheng-ning** [comment]
@andyhuang18 现在的效果是什么样的呢~，明天 DE 会议上可以介绍下进度哈

**Comment by andyhuang18** [comment]
> @andyhuang18 现在的效果是什么样的呢~，明天 DE 会议上可以介绍下进度哈

今晚可以完成，明天可以展示一下

**Comment by wj23027** [comment]
@andyhuang18  @zhicheng-ning😆可以帮我参考一下哪个图标比较合适吗，然后哪种排版比较好看呀

![fe5f14d509f07666826783038eb6794](https://user-images.githubusercontent.com/62098023/219030523-f5ac18b2-79b1-4fa6-9b56-4c484afbf84a.png)

![image](https://user-images.githubusercontent.com/62098023/219030600-0a37b435-815f-49f7-a197-571d4fd7373d.png)

**Comment by zhicheng-ning** [comment]
@will-ww 王老师觉得哪种形式好些呢

**Comment by will-ww** [comment]
> @will-ww 王老师觉得哪种形式好些呢

I prefer the first one~ :-)

**Comment by tyn1998** [comment]
我觉得 单独一列+里面是黄色线条的icon 不错。

**Comment by zhicheng-ning** [comment]
@wj23027 图标可以选择黄色的那种，然后排版，可以单拎出来一列

**Comment by xueqidove** [comment]
> 
Add column name to the icon column: Project Insight

**Comment by zhicheng-ning** [comment]
Hi~ @andyhuang18 ，our big screen has been updated currently, so we hope you can replace the link, the latest link is `https://dataease.nzcer.cn/link/dqMbZrBk`。

eg：

https://dataease.nzcer.cn/link/dqMbZrBk?attachParams=eyJvcmdfbmFtZSI6ImRhdGFlYXNlIiwicmVwb19uYW1lIjoiZGF0YWVhc2UiLCJ0X21vbnRoIjoiMjAyMi0xMi0wMSJ9

![image](https://user-images.githubusercontent.com/39022409/224605590-58fe265f-da52-4fa1-85d4-0b6b917c7879.png)

**Comment by andyhuang18** [comment]
> Hi~ @andyhuang18 ，our big screen has been updated currently, so we hope you can replace the link, the latest link is `https://dataease.nzcer.cn/link/dqMbZrBk`。
> 
> eg：
> 
> [dataease.nzcer.cn/link/dqMbZrBk?attachParams=eyJvcmdfbmFtZSI6ImRhdGFlYXNlIiwicmVwb19uYW1lIjoiZGF0YWVhc2UiLCJ0X21vbnRoIjoiMjAyMi0xMi0wMSJ9](https://dataease.nzcer.cn/link/dqMbZrBk?attachParams=eyJvcmdfbmFtZSI6ImRhdGFlYXNlIiwicmVwb19uYW1lIjoiZGF0YWVhc2UiLCJ0X21vbnRoIjoiMjAyMi0xMi0wMSJ9)
> 
> ![image](https://user-images.githubusercontent.com/39022409/224605590-58fe265f-da52-4fa1-85d4-0b6b917c7879.png)

OK，I will update it right now！

**Comment by will-ww** [comment]
So cool~
