### ISSUE TITLE
[question] Data does not match in leaderboard and other report

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-leaderboard#52]
In open leaderboard, we can see the top 10 project by activity are:
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/37795442/203193854-2ed28098-c1ed-4cb8-bdb3-cfef116fcb8c.png">

But in China Open Source Report 2021, here are:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/37795442/203194132-37153697-289b-40ff-b529-0cdf83a03810.png">

**Comment by zhicheng-ning** [comment]
I guess this situation may be caused by different activity formuals 🤔
