### ISSUE TITLE
[Dev] `prettier` should be enabled in this project ASAP to keep code formatted in same rulse

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-leaderboard#55]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/32434520/218641735-ca62d1d9-8e05-4c07-b1b4-f14c1f22c3fe.png">

Hi guys, I think we should employ a code formatter such as [prettier](https://github.com/prettier/prettier) ASAP :)

**Comment by tyn1998** [comment]
These 3 configuration files in Hypercrx might help:

- https://github.com/hypertrons/hypertrons-crx/blob/ec4c7098aa3aec9b4820a47a6a373e772609eed6/.gitattributes
- https://github.com/hypertrons/hypertrons-crx/blob/ec4c7098aa3aec9b4820a47a6a373e772609eed6/.prettierignore
- https://github.com/hypertrons/hypertrons-crx/blob/ec4c7098aa3aec9b4820a47a6a373e772609eed6/.prettierrc

Format tools supported by your IDE like VSCode will format code according to rules given by `.prettierrc`.

Also put it to [package.json](https://github.com/hypertrons/hypertrons-crx/blob/ec4c7098aa3aec9b4820a47a6a373e772609eed6/package.json#L15) so you can run `npm run prettier` to quickly format all your code.

@wj23027 @andyhuang18 you can have a try 🚀

**Comment by wj23027** [comment]
I can try it~

**Comment by andyhuang18** [comment]
Copy that！
