### ISSUE TITLE
[UI] UI text layout beautification

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-leaderboard#56]
> （GitHub 是全球最大的社交编程及代码托管网站。）

这段话换行截断展示，感觉在 UI 上不是很美观，大家觉得呢 @tyn1998  @andyhuang18 @wj23027 

![image](https://user-images.githubusercontent.com/39022409/219659770-c9ec3095-c06d-44d6-ab17-038ae8e80746.png)

**Comment by tyn1998** [comment]
hh，我觉得删掉就行，看这个网站的谁不知道GitHub呢~

**Comment by wj23027** [comment]
我也觉得可以删掉~
另外openrank指数在这里叫影响力/Influence，我觉得可以就叫openrank，或者适当标注一下，大家觉得呢？
![image](https://user-images.githubusercontent.com/62098023/219683058-91de7d7d-d071-40ac-bdf8-6fb8af2e85b9.png)

**Comment by will-ww** [comment]
> 我也觉得可以删掉~ 另外openrank指数在这里叫影响力/Influence，我觉得可以就叫openrank，或者适当标注一下，大家觉得呢？ 

同意，应该尽量突出 OpenRank 这个词的显示度和认知度~
