### ISSUE TITLE
[Bug] Can't scroll page after clicking top icon

### ISSUE THREAD

**Issue by andyhuang18** [X-lab2017/open-leaderboard#58]
点击置顶图标，在页面置顶后，无法滚动页面。多次点击置顶图标后，才可以取消锁定页面。

![演示](https://user-images.githubusercontent.com/50283262/220248832-4934118d-1298-4cc3-8741-f2f4d785317c.png)

**Comment by tyn1998** [comment]
Hi @andyhuang18，这种Bug配合录屏描述更佳哦~

我看了下#28，发现这个问题并没有被提及。此外，我也测试了一下，除了“ go to top”动画不能被打断外，好像没有遇到“在页面置顶后，无法滚动页面”的问题。

PS：在comment中引用issue或PR，直接井号+数字即可，不需要通过markdown的url语法`[xxx](url)`来添加链接。

**Comment by andyhuang18** [comment]
> 

哦对对，我看错了

**Comment by andyhuang18** [comment]
> Hi @andyhuang18，这种Bug配合录屏描述更佳哦~
> 
> 我看了下#28，发现这个问题并没有被提及。此外，我也测试了一下，除了“ go to top”动画不能被打断外，好像没有遇到“在页面置顶后，无法滚动页面”的问题。
> 
> PS：在comment中引用issue或PR，直接井号+数字即可，不需要通过markdown的url语法`[xxx](url)`来添加链接。

哦对对，我看错了！谢谢学长~

**Comment by andyhuang18** [comment]
上传了演示的视频

https://user-images.githubusercontent.com/50283262/220251288-45210c90-fa95-4551-a5b9-c3c336505f93.mp4

**Comment by tyn1998** [comment]
这是我这儿的情况：

https://user-images.githubusercontent.com/32434520/220251322-0efff8d3-e5dc-40f5-863b-32005fc04da5.mov

**Comment by andyhuang18** [comment]
> 这是我这儿的情况：
> 
> 等到顶了，再等一会会儿呢？

等待后还是无法滚动

**Comment by andyhuang18** [comment]
@wj23027 你那边的情况是正常的吗？

**Comment by wj23027** [comment]
我这边也有这个问题，只有切换到其他模块才能正常滑动

**Comment by tyn1998** [comment]
@gymgym1212 学长和我一样也是Mac所以没暴露出这个问题吧 😆 那拜托你们修一下了~

**Comment by andyhuang18** [comment]
好的好的

**Comment by zhicheng-ning** [comment]
有没有一种可能，是 Edge 浏览器的 bug，我这边用 Chrome 是没问题的，用 Edge 可以复现这个问题

**Comment by wj23027** [comment]
我用Chrome试了一下，还是有这个问题，我用的是windows

**Comment by zhicheng-ning** [comment]
:joy: 那就不清楚了
