### ISSUE TITLE
[Bug] in the global category, does not show a screen icon

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-leaderboard#59]
在设置地区为 **全球** 后，无法显示项目的大屏链接图标

![image](https://user-images.githubusercontent.com/39022409/220250400-94af99ff-60c8-4e86-9e9e-b7c2125bd347.png)

**Comment by andyhuang18** [comment]
收到，马上进行调整

**Comment by wj23027** [comment]
这个是我搞的，之前测试的时候“global”模块很多大屏都没办法正常显示，我以为是暂时没有支持这块，就排除出去了。刚刚我又看了一下，应该是数据缺少了最近的月份才没办法显示。

![image](https://user-images.githubusercontent.com/62098023/220252357-147f80d0-3f36-41ec-9625-7040c264f785.png)

**Comment by zhicheng-ning** [comment]
这是哪个项目，我去数据库里看下

**Comment by wj23027** [comment]
仓库是这个：microsoft/vscode 
大屏链接是这个：http://dataease.nzcer.cn/#/delink?link=iXJ8wbBAwa7PbDwq%2BqT727rnqMN5%2FsVbHA4BpG%2BSH8wfmkpwIvMFZJ%2BgJZH4Lz4w9KvrreN6tmB5CXvrqxl4Ig&user=EpqoHbI53zZ7NNR0xhCn1nXOKC4a8%2FVmA6Zv0tv8ABC5WAtlXGOAIFgS9kaDiaXV7xnhqKG432JiTtyZxZdLuA&attachParams=eyJvcmdfbmFtZSI6Im1pY3Jvc29mdCIsInJlcG9fbmFtZSI6InZzY29kZSIsInRfbW9udGgiOiIyMDIzLTAxLTAxIn0

**Comment by zhicheng-ning** [comment]
刚查了下数据库，估计是没有更新获得 OpenDigger 最新的数据，这个我后面解决

![image](https://user-images.githubusercontent.com/39022409/220254948-8dc3b3df-6def-4abd-9681-c752fd59617d.png)

**Comment by wj23027** [comment]
okok，稍后我调整一下“global“地区的大屏链接
