### ISSUE TITLE
[Chore] to save the messy console

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-leaderboard#64]
I think console output for test purpose should be removed from the codebase:

<img width="1756" alt="image" src="https://user-images.githubusercontent.com/32434520/220518476-58f975d7-6058-42c2-af05-630d8c32ac65.png">

😆

**Comment by andyhuang18** [comment]
Yes~It is time to remove the testing output

**Comment by wj23027** [comment]
I agree with you~

**Comment by frank-zsy** [comment]
I think we can put a variable in the code to enable or disable the output. console output is quite useful for debugging, we can set it to disable on release automatically.

**Comment by kunal8411** [comment]
Hi Team, 

I have raised one PR for this issue can you please check.

PR: https://github.com/X-lab2017/open-leaderboard/pull/93
i have created one env file and stored one variable in that file as "NODE_ENV"  of the value of NODE_ENV is development then only we will be able to see the consoles for debugging, other than dev env the consoles will be hidden.

**Comment by andyhuang18** [comment]
Thank you for your contribution, I will review your commit as soon as possible!
