### ISSUE TITLE
[doc] add contributing section in README

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-leaderboard#69]
we should add contributing section in README for new comer.:laughing:

**Comment by zhicheng-ning** [comment]
@andyhuang18 @wj23027 Could you try it when you are free time

**Comment by wj23027** [comment]
I can try it~

**Comment by TracK92** [comment]
Hello @zhicheng-ning. I've noticed that the README section is not very comprehensive. I wonder if I could add more details to it as well and spruce it up a bit. I have a README template that's quite comprehensive. Let me know 😃

**Comment by zhicheng-ning** [comment]
@TracK92 I'm glad you are willing to contribute to the community, but the issue has been assigned to the others, you can look at other unallocated issues.:joy:
