### ISSUE TITLE
[ui] add clear sheet title in open-leaderboard

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-leaderboard#70]
It's a good idea that we can add “Project insight/Project Screen/Project Board” in sheet title.

![image](https://user-images.githubusercontent.com/39022409/222040741-c11c489b-2e90-4a94-80cb-739f4aada3c1.png)

**Comment by andyhuang18** [comment]
I perfer ```insight board/项目洞察```

**Comment by wj23027** [comment]
I think  `Project Board/洞察大屏` is more appropriate~

**Comment by zhicheng-ning** [comment]
I think all of your suggestions are both good.
