### ISSUE TITLE
[doc] replace Insight board with latest project dashboard picture

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-leaderboard#75]
We need update [Insight board](https://github.com/X-lab2017/open-leaderboard#:~:text=By%20clicking%20on%20the%20%E2%80%9CInsight%20board%E2%80%9D%20%2C%20you%20can%20see%20the%20following%20figure.%20You%20can%20refer%20to%20the%20OpenDigger%20Metric%20for%20detailed%20metrics%20interpretation.) in README cause we publish latest project dashboard, 

**old version:**

![image](https://user-images.githubusercontent.com/39022409/224877222-cbc8d4cd-6b35-43ac-b43b-7d0e545f178e.png)

**latest version:**

![image](https://user-images.githubusercontent.com/39022409/224877074-3ea4ca81-2b82-4c0a-9ba4-3d12d0c51dbe.png)

**Comment by andyhuang18** [comment]
Copy that~
