### ISSUE TITLE
[feature] add a search function for querying repo or developer

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-leaderboard#77]
# description

With the strong needs of users, we need to add a search function for OpenLeaderBoard to search for projects or developers on the list.

- [ ] repo search 
- [ ] developer search

# related issue

- https://github.com/X-lab2017/open-leaderboard/issues/67

**Comment by andyhuang18** [comment]
It's a good idea~I will work on it now.^ ^

**Comment by zhicheng-ning** [comment]
that's great, I suggestion @wj23027 could collaboration with you.

**Comment by wj23027** [comment]
I'd love to work on it with @andyhuang18 ~
