### ISSUE TITLE
[feature] add a unified entrance to all large screens in OpenLeaderBoard

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-leaderboard#79]
We have already made a lot of large screens, and there may be more in the future. Therefore, I think it is possible to add a unified entrance for all large screens in the OpenLeaderBoard, through which you can enter a place similar to a large screen exhibition, and users can freely browse their favorite large screens.

https://github.com/X-lab2017/open-wonderland/issues/242#issuecomment-1480540169

How do you think? @will-ww @andyhuang18 @wj23027

**Comment by andyhuang18** [comment]
Does DataEase support the preview feature? Or we can display the dashboard in the page through ```iframe```, we can add a tab for displaying the series dashboard.

**Comment by zhicheng-ning** [comment]
> Does DataEase support the preview feature?

yep, every dashboard has its display link.

**Comment by andyhuang18** [comment]
Maybe we can add a button to the Header line for jumping to show the series dashboard

![image](https://user-images.githubusercontent.com/50283262/228737137-9151bcd0-93f2-4ad5-b67a-71b7d6e1fac0.png)

**Comment by wj23027** [comment]
We can display the `Developer Insight Board` in a single column in the data table (similar to the `Project Insight Board`), and then create a new partition to display the other macro dashboard.

**Comment by wj23027** [comment]
> Maybe we can add a button to the Header line for jumping to show the series dashboard
> 
> ![image](https://user-images.githubusercontent.com/50283262/228737137-9151bcd0-93f2-4ad5-b67a-71b7d6e1fac0.png)

I agree, and I think we may need a more noticeable icon to distinguish it from the three next to it~

**Comment by andyhuang18** [comment]
> > Maybe we can add a button to the Header line for jumping to show the series dashboard
> > ![image](https://user-images.githubusercontent.com/50283262/228737137-9151bcd0-93f2-4ad5-b67a-71b7d6e1fac0.png)
> 
> I agree, and I think we may need a more noticeable icon to distinguish it from the three next to it~

You're right, that's why I drew the BIG red circles haha. And we can replace the image button with a texta button, which is more suggestive and visible.

**Comment by zhicheng-ning** [comment]
> We can display the `Developer Insight Board` in a single column in the data table (similar to the `Project Insight Board`), and then create a new partition to display other macro dashboards.

Good idea，but currently `Developer Insight Board` isn't support dynmic data like `Project Insight Board`, it just show a static data for a certain developer.

**Comment by andyhuang18** [comment]
OK, I will find a solution.
