### ISSUE TITLE
OpenLeaderBoard 网站增加 DataEase 合作社区 Logo

### ISSUE THREAD

**Issue by xiebei-l** [X-lab2017/open-leaderboard#81]
OpenLeaderBoard 网站增加 DataEase 合作社区 Logo，Logo 如果模糊可以联系提供压缩文件
![DataEase-01](https://user-images.githubusercontent.com/70566485/231071204-b85498a9-f8d9-436f-8375-bcde92b679eb.png)

**Comment by andyhuang18** [comment]
好的，我马上着手添加~
