### ISSUE TITLE
[suggestion]建议 OpenLeaderBoard 网站下方数据支持、官方支持、合作社区放成一排

### ISSUE THREAD

**Issue by xiebei-l** [X-lab2017/open-leaderboard#83]
建议 OpenLeaderBoard 网站下方数据支持、官方支持、合作社区放成一排，大概示例如下，可供参考
![拼接](https://user-images.githubusercontent.com/70566485/231725459-532e92d2-a275-4390-8ce2-5f330a3e7a3e.png)

**Comment by tyn1998** [comment]
+1 非常赞同~

**Comment by andyhuang18** [comment]
是很好的建议！我稍后会进行调整，谢谢你的提议~
