### ISSUE TITLE
[Bug] OpenLeaderBoard项目开源大屏每月大概1-3号大屏缺失内容

### ISSUE THREAD

**Issue by xiebei-l** [X-lab2017/open-leaderboard#95]
### Current Behavior

<img width="1465" alt="image" src="https://github.com/X-lab2017/open-leaderboard/assets/70566485/d0f53432-8de1-4630-a5a0-121491f02483">

### Expected Behavior

希望解决方案可以避免当前缺失数据的情况，缺失数据比较影响用户体验。
基于这种情况是不是可以考虑传递的参数进行处理，避免出现大屏缺失数据的问题呢？

### Environment

```markdown
- OS:
- Browser:
```

**Comment by andyhuang18** [comment]
我来解决这个问题。

我会在OpenLeaderboard前端对日期做更加精细的逻辑判断。目前的想法是，在每个月1-3号，用户查看前一个月数据时，展示上上个月的数据并提示最新的前一个月数据还未更新。比如当用户在`2023-07-01`访问`2023-06`的数据时，前端会展示`2023-05`的数据。

如果有什么建议可以告诉我，谢谢！

**Comment by andyhuang18** [comment]
由于目前这个修改的版本会给用户歧义，因此我会重新对其进行修改。调整后的思路是，当数据还未更新时，禁用月份选项查看前一个月的数据，并在主界面通知用户。

**Comment by wj23027** [comment]
> 由于目前这个修改的版本会给用户歧义，因此我会重新对其进行修改。调整后的思路是，当数据还未更新时，禁用月份选项查看前一个月的数据，并在主界面通知用户。

我觉得可以在这里直接备注：当前数据更新到xx年xx月（每月4号更新上月数据）。在没更新的那几天另外提示反而会比较难理解

![1686030598776](https://github.com/X-lab2017/open-leaderboard/assets/62098023/76fdc4ea-c165-4dd4-927a-908992a06558)
