### ISSUE TITLE
[Bug] Data is not the newest

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-leaderboard#99]
### Current Behavior

I updated the leaderboard for 2023.6 and the [`meta.json`](https://xlab-open-source.oss-cn-beijing.aliyuncs.com/open_leaderboard/meta.json) file contains the correct timestamp, but the leaderboard still only shows the data for 2023.5 as the newest month.

### Expected Behavior

If the `meta.json` file gives a timestamp in 2023.7, then it means the data for 2023.6 has been updated, so it should be the newest data. Which means all the behavior of the leaderboard should depend on the `meta.json` file.

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

**Comment by andyhuang18** [comment]
It used to be updated at a fixed time. If there is `meta.json` now, it can be updated more accurately. I will modify the update logic of openleaderboard as soon as possible
